name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build TypeScript
        run: npx tsc

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Deploy files and restart server
        run: |
          cd web_page
          pm2 stop index.js
          cp -r client/build/ /web_page/public/
          cp -r dist/ /web_page/
          cp package.json /web_page/
          npm install
          npm audit fix
          pm2 start index.js
